### PR TITLE
Truncate slug when source field is longer than configured maxLength;

### PR DESCRIPTION
**Pull request by curtisgibby**
add tests for max length and custom max length;
refs https://github.com/UseMuffin/Slug/issues/21 ;

### CODE REVIEW

**Comment by jadb** [comment]
Looking good! There is a related failing test on Postgres, once fixed, this can be merged.

**Comment by curtisgibby** [comment]
The [Postgres failures](https://travis-ci.org/UseMuffin/Slug/jobs/136570260) complain about a string being truncated at 255 characters. If I understand what's going on with that failure, it's not the *slug* that's getting truncated by Postgres, it's the source field -- the ["extremely long title"](https://github.com/curtisgibby/Slug/blob/e83a485e231fb209bd61381511c0e333d28babbf/tests/TestCase/Model/Behavior/SlugBehaviorTest.php#L255) itself. How are we supposed to test that our intentional truncation on the slug field works correctly without also specifying a too-long source field that will itself get unintentionally truncated?

I could just drop my [`testMaxLength` test](https://github.com/curtisgibby/Slug/blob/e83a485e231fb209bd61381511c0e333d28babbf/tests/TestCase/Model/Behavior/SlugBehaviorTest.php#L250-L270) altogether, but I believe that would defeat the purpose of unit testing.

How would you suggest that I proceed?

**Comment by Phillaf** [comment]
This implementation fails to cover the case where a suffix is added to get a unique slug.

Trucate is called in the `_slug` method, an `$unique()` might add a suffix to the string afterward. [ref](https://github.com/curtisgibby/Slug/blob/e83a485e231fb209bd61381511c0e333d28babbf/src/Model/Behavior/SlugBehavior.php#L266-L270)

This is an interesting problem as the suffix should never be truncated, and the uniqueness should be checked on the already truncated string.

> How are we supposed to test that our intentional truncation on the slug field works correctly without also specifying a too-long source field that will itself get unintentionally truncated?

Use 2 [database fields of different lengths](https://github.com/UseMuffin/Slug/blob/master/tests/Fixture/TagsFixture.php#L13-L14) maybe?

**Comment by curtisgibby** [comment]
> This implementation fails to cover the case where a suffix is added to get a unique slug.

I believe that the [second assert in this test](https://github.com/curtisgibby/Slug/blob/e83a485e231fb209bd61381511c0e333d28babbf/tests/TestCase/Model/Behavior/SlugBehaviorTest.php#L262-L267) *does* cover that case. The initial `_slug` truncate call generates the same "extremely-long" slug as the first record, which then gets [checked by `_uniqueSlug`](https://github.com/curtisgibby/Slug/blob/e83a485e231fb209bd61381511c0e333d28babbf/src/Model/Behavior/SlugBehavior.php#L298-L305), which truncates it again according to the length of both the slug and the suffix, then appends the suffix.

**Comment by curtisgibby** [comment]
> Use 2 database fields of different lengths maybe?

Interesting idea.

1. Bump the Tag `name` length to, say, 300 characters in the fixture.
2. In the test, pass an extremely long `name` (of more than 255 but less than 300 characters) that will correctly save there, but would need to be truncated by the `slug` field (still at 255 characters).

 @jadb are you cool if I make that change to the fixture?

**Comment by curtisgibby** [comment]
How does coveralls determine code coverage? I've never dealt with it before, but I have no idea how the coverage could have decreased, given that i added *more* testing than we had before.

**Comment by bravo-kernel** [comment]
@curtisgibby Coveralls checks which parts of the code are covered by tests so it could mean the tests you added are not covering new code.

1. Check the coveralls build details https://coveralls.io/builds/6551892
2. Open one of the files in red (e.g. `src/Slugger/CocurSlugger.php` in this case)
3. The file will highlight untested parts of that file
4. Create a test for it
5. Re-commit
6. Watch the file get green

**Comment by curtisgibby** [comment]
But I didn't create or modify `src/Slugger/CocurSlugger.php` or the Cake slugger. The code that calls those sluggers is already in place in the released version of the plugin. Why didn't coveralls think that those `slug` methods needed to be covered at the time that they were added? In other words, how did my change actually affect the code coverage?

**Comment by jadb** [comment]
@curtisgibby probably coveralls wasn't implemented when that file was added.

In any case, this LGTM now. Thanks!

**Comment by curtisgibby** [comment]
Should also close #21

**Pull request merged**
