### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ADmad**
- Made sluggers non-static
- Added config for sluggers
- Cake slugger now lowercases slug by default (which is common usecase and concur/slugify does it too)

### CODE REVIEW

**Comment by ADmad** [comment]
I am still not very happy with the sluggers. For e.g. you can't set rulesset for a `\Concur\Slugify` instance which is probably the only reason why one would chose to use the `ConcurSlugger`.

**Comment by ADmad** [comment]
Hmm could add a magic `__call()` method to `ConcurSlugger` to forward the calls to `Concur\Slugify` instance.

Maybe we can also rename `SluggerInterface::slug()` to `SluggerInterface::slugify()` so that one can just set a `Concur\Slugify` instance as slugger.

**Comment by ADmad** [comment]
We also also just provide a more generic option which doesn't for specific method name allow using any callable. For e.g. like this [method](https://github.com/cviebrock/eloquent-sluggable#method) option.

**Comment by jadb** [comment]
Made a tiny CS fix. 

I like the `method` option. Would you add it to this PR or a separate one?

**Comment by ADmad** [comment]
> I like the method option. Would you add it to this PR or a separate one?

Already done. You can set a callable for `slugger` option. Check the test case `testCallableForSlugger`.

**Comment by jadb** [comment]
:+1:

**Pull request merged**
