### PR TITLE
Allow regenerating slug on record updating

### LINKED ISSUE #8: Slug not created when editing a record
I have an existing table I have been using for a while and contains records. I have added the Slug plugin appropriately, keeping all the defaults.

Slugs are created for newly added records, but are not created when an existing record is edited.

I appreciate this might not be desired behaviour (I can imagine slugs changing could upset a lot of people) but is it possible to create a slug when editing an existing record only when the 'slug' field is empty? This way, existing slugs will not be automatically changed when other fields in the record are edited (although this could be configurable behaviour?) but slugs will be created for empty fields.

### PR DESCRIPTION
**Pull request by ADmad**
Closes #8

### CODE REVIEW

**Comment by bravo-kernel** [comment]
:clap:

**Comment by jadb** [comment]
Nice one. 

Just a thought am throwing here: make it work like `[TimestampBehavior](https://github.com/cakephp/cakephp/blob/master/src/ORM/Behavior/TimestampBehavior.php#L50-L53)` and allow for a type of matrix configuration (different events, different options)?

**Comment by ADmad** [comment]
@jadb Timestamp handles multiple fields while in this case it's just one. So while similar could be done I say meh.

**Comment by jadb** [comment]
Works for me!

**Pull request merged**
